### ISSUE TITLE
code-execution-api-demo link broken

### ISSUE THREAD

**Issue by Jahhein** [ethanchewy/PythonBuddySandboxed#2]
404 error on line 3.

[code-execution-api-demo](https://github.com/christophxetd/code-execution-api-demo)

His username is a bit odd. I got the fix.

**Comment by ethanchewy** [comment]
https://github.com/ethanchewy/PythonBuddySandboxed/commit/77ec2ecebb714a8b9d9d92bd2deca18709c9f81d
