### ISSUE TITLE
Fix Markdown Typo

### ISSUE THREAD

**Issue by Deniernal354** [ethanchewy/PythonBuddySandboxed#4]
![image](https://user-images.githubusercontent.com/31352787/47634851-fd236280-db63-11e8-9896-fa7e1695c980.png)

There should not be a space between the array brackets `]` and the normal parentheses (brackets) `(`
It should look like this `Created off of [christophetd/code-execution-api-demo](https://github.com/christophetd/code-execution-api-demo)`

**Comment by Jahhein** [comment]
Im on it and still am fixing the readme

**Comment by ethanchewy** [comment]
fixed: https://github.com/ethanchewy/PythonBuddySandboxed/commit/77ec2ecebb714a8b9d9d92bd2deca18709c9f81d
